-- Athletiza - estrutura do banco de dados (PostgreSQL)
-- Pode ser executado novamente: apaga e recria todas as tabelas (os dados são perdidos).
--
-- Regras de exclusão (RN16):
--   RESTRICT -> impede excluir um registro que ainda é usado em outro lugar
--   CASCADE  -> apaga junto as linhas que só existem por causa do registro principal
--               (ex.: presenças de um treino, tarefas de um evento)

DROP TABLE IF EXISTS registro CASCADE;
DROP TABLE IF EXISTS arquivo CASCADE;
DROP TABLE IF EXISTS pasta CASCADE;
DROP TABLE IF EXISTS tarefa CASCADE;
DROP TABLE IF EXISTS evento_responsavel CASCADE;
DROP TABLE IF EXISTS evento CASCADE;
DROP TABLE IF EXISTS compromisso CASCADE;
DROP TABLE IF EXISTS resultado CASCADE;
DROP TABLE IF EXISTS competicao_atleta CASCADE;
DROP TABLE IF EXISTS competicao_modalidade CASCADE;
DROP TABLE IF EXISTS competicao CASCADE;
DROP TABLE IF EXISTS presenca_treino CASCADE;
DROP TABLE IF EXISTS treino CASCADE;
DROP TABLE IF EXISTS gestao_membro_cargo CASCADE;
DROP TABLE IF EXISTS cargo CASCADE;
DROP TABLE IF EXISTS gestao CASCADE;
DROP TABLE IF EXISTS atleta_modalidade CASCADE;
DROP TABLE IF EXISTS atleta CASCADE;
DROP TABLE IF EXISTS modalidade CASCADE;
DROP TABLE IF EXISTS membro CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;

-- ===================== Pessoas =====================

CREATE TABLE usuario (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(100) NOT NULL,
    matricula   VARCHAR(20),
    contato     VARCHAR(100),
    login       VARCHAR(50)  NOT NULL UNIQUE,
    senha_hash  VARCHAR(255) NOT NULL,
    perfil      VARCHAR(20)  NOT NULL CHECK (perfil IN ('ADMINISTRADOR', 'DIRETORIA', 'CONSULTA')),
    ativo       BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE membro (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(100) NOT NULL,
    matricula   VARCHAR(20)  NOT NULL UNIQUE,
    contato     VARCHAR(100),
    situacao    VARCHAR(20)  NOT NULL DEFAULT 'ATIVO' CHECK (situacao IN ('ATIVO', 'INATIVO'))
);

CREATE TABLE modalidade (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(50)  NOT NULL,
    genero      VARCHAR(20)  NOT NULL CHECK (genero IN ('MASCULINO', 'FEMININO', 'MISTO')),
    UNIQUE (nome, genero)
);

CREATE TABLE atleta (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(100) NOT NULL,
    matricula       VARCHAR(20)  NOT NULL UNIQUE,
    contato         VARCHAR(100),
    data_nascimento DATE,
    situacao        VARCHAR(20)  NOT NULL DEFAULT 'ATIVO' CHECK (situacao IN ('ATIVO', 'INATIVO')),
    observacoes     VARCHAR(500)
);

CREATE TABLE atleta_modalidade (
    atleta_id     INTEGER     NOT NULL REFERENCES atleta (id) ON DELETE CASCADE,
    modalidade_id INTEGER     NOT NULL REFERENCES modalidade (id) ON DELETE RESTRICT,
    situacao      VARCHAR(20) NOT NULL DEFAULT 'ATIVO'
                  CHECK (situacao IN ('ATIVO', 'LESIONADO', 'AFASTADO', 'INATIVO')),
    PRIMARY KEY (atleta_id, modalidade_id)
);

-- ===================== Gestão =====================

CREATE TABLE gestao (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(100) NOT NULL UNIQUE,
    data_inicio DATE         NOT NULL,
    data_fim    DATE         NOT NULL,
    descricao   VARCHAR(500),
    situacao    VARCHAR(20)  NOT NULL CHECK (situacao IN ('PLANEJADA', 'EM_ANDAMENTO', 'ENCERRADA')),
    CHECK (data_fim >= data_inicio)
);

CREATE TABLE cargo (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome              VARCHAR(60) NOT NULL UNIQUE,
    ordem             INTEGER     NOT NULL DEFAULT 1,
    cargo_superior_id INTEGER     REFERENCES cargo (id) ON DELETE SET NULL
);

CREATE TABLE gestao_membro_cargo (
    gestao_id INTEGER NOT NULL REFERENCES gestao (id) ON DELETE CASCADE,
    membro_id INTEGER NOT NULL REFERENCES membro (id) ON DELETE RESTRICT,
    cargo_id  INTEGER NOT NULL REFERENCES cargo (id) ON DELETE RESTRICT,
    PRIMARY KEY (gestao_id, membro_id, cargo_id)
);

-- ===================== Treinos =====================

CREATE TABLE treino (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo           VARCHAR(20)  NOT NULL CHECK (tipo IN ('TREINO', 'AMISTOSO')),
    titulo         VARCHAR(100) NOT NULL,
    data           DATE         NOT NULL,
    horario        TIME,
    local          VARCHAR(100),
    modalidade_id  INTEGER      NOT NULL REFERENCES modalidade (id) ON DELETE RESTRICT,
    responsavel_id INTEGER      REFERENCES membro (id) ON DELETE SET NULL,
    adversario     VARCHAR(100),
    resultado      VARCHAR(100),
    observacoes    VARCHAR(500)
);

CREATE TABLE presenca_treino (
    treino_id INTEGER NOT NULL REFERENCES treino (id) ON DELETE CASCADE,
    atleta_id INTEGER NOT NULL REFERENCES atleta (id) ON DELETE RESTRICT,
    presente  BOOLEAN NOT NULL,
    PRIMARY KEY (treino_id, atleta_id)
);

-- ===================== Competições =====================

CREATE TABLE competicao (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo      VARCHAR(100) NOT NULL,
    data        DATE         NOT NULL,
    data_fim    DATE,
    horario     TIME,
    local       VARCHAR(100),
    situacao    VARCHAR(20)  NOT NULL CHECK (situacao IN ('PLANEJADA', 'CONFIRMADA', 'ENCERRADA', 'CANCELADA')),
    observacoes VARCHAR(500),
    CHECK (data_fim IS NULL OR data_fim >= data)
);

CREATE TABLE competicao_modalidade (
    competicao_id INTEGER NOT NULL REFERENCES competicao (id) ON DELETE CASCADE,
    modalidade_id INTEGER NOT NULL REFERENCES modalidade (id) ON DELETE RESTRICT,
    PRIMARY KEY (competicao_id, modalidade_id)
);

CREATE TABLE competicao_atleta (
    competicao_id INTEGER NOT NULL,
    modalidade_id INTEGER NOT NULL,
    atleta_id     INTEGER NOT NULL REFERENCES atleta (id) ON DELETE RESTRICT,
    PRIMARY KEY (competicao_id, modalidade_id, atleta_id),
    FOREIGN KEY (competicao_id, modalidade_id)
        REFERENCES competicao_modalidade (competicao_id, modalidade_id) ON DELETE CASCADE
);

CREATE TABLE resultado (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competicao_id INTEGER NOT NULL,
    modalidade_id INTEGER NOT NULL,
    atleta_id     INTEGER REFERENCES atleta (id) ON DELETE RESTRICT,
    colocacao     INTEGER CHECK (colocacao IS NULL OR colocacao > 0),
    placar        VARCHAR(50),
    observacao    VARCHAR(500),
    FOREIGN KEY (competicao_id, modalidade_id)
        REFERENCES competicao_modalidade (competicao_id, modalidade_id) ON DELETE CASCADE
);

-- ===================== Eventos e calendário =====================

CREATE TABLE evento (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo      VARCHAR(100) NOT NULL,
    tipo_evento VARCHAR(20)  NOT NULL
                CHECK (tipo_evento IN ('FESTA', 'ACAO_SOCIAL', 'ACAO_AMBIENTAL', 'COMPETICAO', 'OUTRO')),
    data        DATE         NOT NULL,
    horario     TIME,
    local       VARCHAR(100),
    descricao   VARCHAR(500),
    situacao    VARCHAR(20)  NOT NULL CHECK (situacao IN ('PLANEJADO', 'CONFIRMADO', 'REALIZADO', 'CANCELADO')),
    observacoes VARCHAR(500)
);

CREATE TABLE evento_responsavel (
    evento_id INTEGER NOT NULL REFERENCES evento (id) ON DELETE CASCADE,
    membro_id INTEGER NOT NULL REFERENCES membro (id) ON DELETE RESTRICT,
    PRIMARY KEY (evento_id, membro_id)
);

CREATE TABLE tarefa (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id      INTEGER REFERENCES evento (id) ON DELETE CASCADE,
    competicao_id  INTEGER REFERENCES competicao (id) ON DELETE CASCADE,
    descricao      VARCHAR(200) NOT NULL,
    responsavel_id INTEGER      REFERENCES membro (id) ON DELETE RESTRICT,
    prazo          DATE,
    situacao       VARCHAR(20)  NOT NULL DEFAULT 'PENDENTE'
                   CHECK (situacao IN ('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDA'))
);

CREATE TABLE compromisso (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo      VARCHAR(100) NOT NULL,
    data        DATE         NOT NULL,
    horario     TIME,
    local       VARCHAR(100),
    observacoes VARCHAR(500)
);

-- ===================== Registros (galeria de fotos e vídeos) =====================
-- O arquivo em si fica no disco (pasta de mídias); aqui ficam apenas as informações dele.

CREATE TABLE pasta (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(60) NOT NULL UNIQUE,
    criada_em TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE arquivo (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pasta_id    INTEGER      NOT NULL REFERENCES pasta (id) ON DELETE RESTRICT,
    nome        VARCHAR(150) NOT NULL,
    caminho     VARCHAR(300) NOT NULL UNIQUE,
    tipo        VARCHAR(10)  NOT NULL CHECK (tipo IN ('IMAGEM', 'VIDEO')),
    tamanho     BIGINT       NOT NULL CHECK (tamanho >= 0),
    enviado_em  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    enviado_por VARCHAR(50),
    descricao   VARCHAR(500)
);

CREATE INDEX idx_treino_data ON treino (data);
CREATE INDEX idx_competicao_data ON competicao (data);
CREATE INDEX idx_evento_data ON evento (data);
CREATE INDEX idx_compromisso_data ON compromisso (data);
CREATE INDEX idx_arquivo_pasta ON arquivo (pasta_id);
