-- Migração da branch 0011: troca o histórico de operações pela galeria de registros.
-- Use apenas se você já tem dados no banco e não quer rodar 01_estrutura.sql de novo.
-- Pode ser executado mais de uma vez.

DROP TABLE IF EXISTS registro;

CREATE TABLE IF NOT EXISTS pasta (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(60) NOT NULL UNIQUE,
    criada_em TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS arquivo (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pasta_id    INTEGER      NOT NULL REFERENCES pasta (id) ON DELETE RESTRICT,
    nome        VARCHAR(150) NOT NULL,
    caminho     VARCHAR(300) NOT NULL UNIQUE,
    tipo        VARCHAR(10)  NOT NULL CHECK (tipo IN ('IMAGEM', 'VIDEO')),
    tamanho     BIGINT       NOT NULL CHECK (tamanho >= 0),
    enviado_em  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    enviado_por VARCHAR(50),
    descricao   VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS idx_arquivo_pasta ON arquivo (pasta_id);

INSERT INTO pasta (nome) VALUES ('Festas'), ('Ações Sociais'), ('Competições'), ('Treinos'), ('Outros')
ON CONFLICT (nome) DO NOTHING;
